// src/components/molecules/Card.svelte
<script lang="ts">
	import Icon from '@iconify/svelte';
	import { readableDate } from '../utils.js';
	import Pill from './atoms/Pill.svelte';
	import Button from './atoms/Button.svelte';

	export let highlight = false;
	export let Cover = 'http://placeimg.com/320/240/tech';
	export let Zone = 'Centro';
	export let Neighborhood = 'Lapa';
	export let Music = 'Funk';
	export let event = {
		Title: 'Festa no Lugar X',
		Date: `2022-02-01T23:30:00.000Z`,
		Ticket: ''
	};
</script>

<div class="card">
	<span class="hover:cursor-pointer" on:click>
		<img class="card-cover" src={Cover} alt="" />
		<div class="card-date">{readableDate(event.Date)}</div>
		<div class="card-title">{event.Title}</div>
	</span>

	<div class="pills-wrapper">
		{#if Zone}
			<Pill {highlight} on:click={() => alert('new tab | api request by neighborhood')}>
				{Zone}
			</Pill>
		{/if}

		{#if Neighborhood}
			<Pill {highlight} on:click={() => alert('new tab | api request by neighborhood')}>
				{Neighborhood}
			</Pill>
		{/if}

		{#if Music}
			<Pill {highlight} on:click={() => alert('new tab | api request by neighborhood')}>
				{Music}
			</Pill>
		{/if}
	</div>

	<div>
		<Button {highlight} on:click={() => alert('new tab | pagina de ingresso')}>
			<Icon class="mr-1 text-2xl" icon="material-symbols:airplane-ticket-rounded" /> Comprar Ingressos
		</Button>
	</div>
</div>

<style lang="postcss">
	.card {
		@apply backdrop-blur-md bg-white/5 rounded-lg p-5;

		.card-cover {
			@apply w-full h-60 object-cover rounded-lg mb-3;
		}

		.card-date {
			@apply text-xl text-white mb-1;
		}

		.card-title {
			@apply text-3xl font-bold text-white;
		}

		.pills-wrapper {
			@apply my-3;
		}
	}
</style>

// src/components/molecules/Card.tsx
import Pill from "../atoms/Pill";
import Button from "../atoms/Button";

function goto(url: string) {
  return "";
}

export type EventData = any;
// export type EventData = {
//   date: string;
//   title: string;
//   cover: { url: string };
//   neighborhood: { id: number; title: string };
//   zone: { id: number; title: string };
//   mood: { id: number; title: string };
// };

export type CardProps = {
  event: EventData;
  highlight: boolean;
  cover: string;
  neighborhood?: string;
  zone?: string;
  mood?: string;
  onClick?: () => void;
};

const Card = ({ event, cover, neighborhood, zone, mood }: CardProps) => {
  return (
    <div className="card">
      <span className="hover:cursor-pointer" onClick={() => {}}>
        <img className="card-cover" src={cover} alt="" />
        <div className="card-date">{event.date}</div>
        <div className="card-title">{event.title}</div>
      </span>

      <div className="card-meta">
        {zone ? <Pill highlight>{zone}</Pill> : null}

        {neighborhood ? <Pill highlight>{neighborhood}</Pill> : null}

        {mood ? <Pill highlight>{mood}</Pill> : null}
      </div>

      <div className="card-bottom">
        <Button highlight>
          {/* <Icon
            className="mr-1 text-2xl"
            icon="material-symbols:airplane-ticket-rounded"
          />{" "} */}
          Comprar Ingressos
        </Button>
      </div>
    </div>
  );
};

export default Card;
