// src/components/organisms/TopBlock.svelte
<script lang="ts">
	import Header from '../molecules/Header.svelte';
	import SearchBlock from '../molecules/SearchBlock.svelte';
</script>

<Header />

<section id="top" class="grid grid-cols-1">
	<img class="sextou-logo" src="/sextou_kv.png" alt="Sextou!" />

	<SearchBlock />
</section>

<style lang="postcss">
	.sextou-logo {
		@apply mx-auto mt-20 px-3 xl:mt-32;
	}
</style>

// _spa/src/components/organisms/TopBlock.tsx
import { Link } from 'react-router-dom';
import Sextou from '../../assets/sextou.png';

import './TopBlock.pcss';

function TopBlock() {
  return (
    <section id="top" className="grid grid-cols-1">
      <Link to="/" reloadDocument>
        <img className="sextou-logo" src={Sextou} alt="Sextou!" />
      </Link>

      {/* <SearchBlock /> */}
    </section>
  );
}

export default TopBlock;
